import useCheckSession from 'hooks/useCheckSession';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { node } from 'prop-types';
import React, { useEffect } from 'react';

const Layout = ({ children }) => {
    const router = useRouter();
    const { session } = useCheckSession();
    useEffect(() => {
        if (!session) router.push('/login');
    }, []);
    if (!session) return null;
    const content = 'JS Playground Web generated by Next js';
    return (
        <>
            <Head>
                <title>Dion Fananie&#39;s React Playground</title>
                <meta name="description" content={content} />
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content={content} />
                <meta property="og:type" content="website" />
                <meta name="og:title" property="og:title" content={content} />
                <meta name="og:description" property="og:description" content={content} />
                <meta property="og:site_name" content="Next Dion Fananie" />
                <meta property="og:url" content="https://next.dionfananie.com/" />
                <meta name="twitter:card" content="summary" />
                <meta name="twitter:title" content="Next Dion Fananie" />
                <meta name="twitter:description" content={content} />
                <meta name="twitter:site" content={content} />
                <meta name="twitter:creator" content="Dion Fananie" />
                <link rel="icon" type="image/png" href="/favicon.ico" />
                <link rel="apple-touch-icon" href="/favicon.ico" />
                <meta property="og:image" content="" />
                <meta name="twitter:image" content="" />
                <link rel="canonical" content="https://next.dionfananie.com/" />
            </Head>
            <div>{children}</div>
        </>
    );
};
Layout.propTypes = {
    children: node.isRequired
};
export default Layout;
